TRAIN:
    # Number of training epochs
    epochs: 180 # original 90
    
    # Architecture name, see pytorch models package for
    # a list of possible architectures
    arch: 'wide-resnet'

    # Starting epoch
    start_epoch: 0

    # SGD paramters
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0002

    # Print frequency, is used for both training and testing
    print_freq: 10

    # Dataset mean and std used for data normalization
    mean: !!python/tuple [0.4914, 0.4822, 0.4465]
    std: !!python/tuple [0.2471, 0.2435, 0.2616]
    
ADV:
    # FGSM parameters during training
    clip_eps: 8.0
    fgsm_step: 2.0

    # Number of repeats for free adversarial training
    n_repeats: 8

    # PGD attack parameters used during validation
    # the same clip_eps as above is used for PGD
    pgd_attack: 
    - !!python/tuple [10, 0.00392156862] #[10 iters, 1.0/255.0]
    - !!python/tuple [50, 0.00392156862] #[50 iters, 1.0/255.0]
    
DATA:
    # Number of data workers
    workers: 4

    # Training batch size
    batch_size: 50

    # Image Size
    img_size: 256

    # Crop Size for data augmentation
    crop_size: 32

    # Color value range
    max_color_value: 255.0

    
